server:
  port: 8080

spring:
  application:
    name: RichLife-Gateway

  cloud:
    gateway:
      routes:
        - id: RichLife-Topic-POST
          uri: lb://RichLife-Topic
          predicates:
            - Path=/api/v1/topic
            - Method=POST
          filters:
            - AuthenticationFilter

        - id: RichLife-Topic-Other
          uri: lb://RichLife-Topic
          predicates:
            - Path=/api/v1/topic/**
            - Method=GET,PUT,DELETE

        - id: RichLife-User
          uri: lb://RichLife-User
          predicates:
            - Path=/api/v1/auth/**
        
        - id: Swagger-Topic
          uri: lb://RichLife-Topic
          predicates:
            - Path=/topic/v3/api-docs

        - id: Swagger-User
          uri: lb://RichLife-User
          predicates:
            - Path=/auth/v3/api-docs

admin:
  protected:
    post-paths: /api/v1/topic

jwt:
  secret-key: 94b83cf0b942b22cc7c98924f90eec3bc90b974d61392b4eb694b85f7c68265e

springdoc:
  swagger-ui:
    urls:
      - name: RichLife-Topic
        url: /topic/v3/api-docs
      - name: RichLife-User
        url: /auth/v3/api-docs

# ===========================
# 5. Eureka Configuration
# ===========================
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: https://richlife-eurekaserver:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    richlife.gateway: DEBUG
